language: node_js
node_js:
  - "9"

deploy:
  provider: npm
  email: 
    secure: "de6SgXAG4Db9GhUtlZE/1HJH2KjbGLcuxzIzRzJQkU56saI0LFwZMa0rV4YCl7GWd4MhB7bkfNQmbN6tOLo281l/SoU5BSU95V+qlLZLTMooyIivbRuRcHvnRp8QtBgy8ZM3EQfJihOyNt0CxPIsiYDu1DE/6Tc2K7cFTweH9jgSkq9lFBLn4TAVXef65FgRDWvFHcf7baDeJ39ZVamHjuqMMCCQobeNZxs/5quGxv8ln9ghrbIEOVwUDaDyg8I150ZgQhur2hqm1SXln6o/wPbbxJxzym3Ebe7j3St6mwnfL7GVP9h+OykAyib+vld159lbkqqaj7mh+THOf1D37qHQSe2LLfVT9jE8gpBQjiIlM1IeYo0/UiCuYDp0wKA3+PwfRzQP52ZfprENcfW8JeNztTsjnp7nhc0XZx9JpY9jIavEDoc5mzBFMUMFgkGeDuArw9CMNZIaL2tvlHMjldkd17PFKAopxTnSNmE0iESQxV/VLmqwhPG3riVOQ0tgDPZwN2/u97TWCFIXiKYqvFiAfpYvW6+nZEn8Cfxcm+C909kHAWCKHsEUxpz2Tdt6Sri0lzeo6WybIqqFIztbedEKkybrG6rUs5GbCDvX1Vbw8I3G5ls7QmzYfil5ZPo0xxDRjN/9HdlOPAolqqBa7uRQuaixLvb3TRX2ahIHGa8="
  api_key:
    secure: "wMqZZhqNoWbDwzn3ECV2bblnektrXthoutez32S2amn33sQnSQ4VwXXlKMQsAvGZsHOtwTCCDPNmIban6RUKoreiGUDpQ9OmVSstuLY2KgdG8JnVppz9PFFeTgUxOzz7oPkdjXPIahL3BY4LNKQlpw1tq7aEBwwc9UkEDYFzfqjSksq3pT6BtiDDCgzvjthqgEYkGQbKQ+PrS5ddFTi+/d/aiBcky5UrzEPn1fgjOBFrimWYQw18rhv/1Uzgifv24g1zrF3fTD+lhY2sA9qN+VAillXG2lyca1qkMG+DqqbkpJx0jNbZC5NsK7fPb6p3oiEzplzC4NNYHpHYl9fxt1PwbvYBTme1eBYZyZbZS0WpG1pUZOp9LJWJUfgox15+DUCyO/VXG6djzpLJras1dbjBv0sBzptcxVnT9YSE9HMZLPG2EtpMhVg01bE9619H3e41AHA1AkGKIAOSDdlEnnMqid+jvXOl+KbTCZcHchEK+GCfmhGtcI+i0o0Sl1i4u61xXl51BZfXGo7pmlsj4yyWYPWImzx93XfYW7Xnf+Ec9jCdXXh55vTyG851a3g+h04pZrYj44UoB/IAyFN9wSeqFYFp5OcEy96WyHqLAGUpb3hv4tIIbaDM1NZn8KZhMjWUev8Y3uGjxrCthAw37jbrnxbH0/FNoFIpFPM19xs="
  skip_cleanup: true
  on:
    branch: master
    tags: true
