language: node_js
node_js:
  - "9"

deploy:
  provider: npm
  email: 
    secure: "de6SgXAG4Db9GhUtlZE/1HJH2KjbGLcuxzIzRzJQkU56saI0LFwZMa0rV4YCl7GWd4MhB7bkfNQmbN6tOLo281l/SoU5BSU95V+qlLZLTMooyIivbRuRcHvnRp8QtBgy8ZM3EQfJihOyNt0CxPIsiYDu1DE/6Tc2K7cFTweH9jgSkq9lFBLn4TAVXef65FgRDWvFHcf7baDeJ39ZVamHjuqMMCCQobeNZxs/5quGxv8ln9ghrbIEOVwUDaDyg8I150ZgQhur2hqm1SXln6o/wPbbxJxzym3Ebe7j3St6mwnfL7GVP9h+OykAyib+vld159lbkqqaj7mh+THOf1D37qHQSe2LLfVT9jE8gpBQjiIlM1IeYo0/UiCuYDp0wKA3+PwfRzQP52ZfprENcfW8JeNztTsjnp7nhc0XZx9JpY9jIavEDoc5mzBFMUMFgkGeDuArw9CMNZIaL2tvlHMjldkd17PFKAopxTnSNmE0iESQxV/VLmqwhPG3riVOQ0tgDPZwN2/u97TWCFIXiKYqvFiAfpYvW6+nZEn8Cfxcm+C909kHAWCKHsEUxpz2Tdt6Sri0lzeo6WybIqqFIztbedEKkybrG6rUs5GbCDvX1Vbw8I3G5ls7QmzYfil5ZPo0xxDRjN/9HdlOPAolqqBa7uRQuaixLvb3TRX2ahIHGa8="
  api_key:
    secure: "mtrTADG350rHIRUM/tGrU9v5ditH7ePk9a8p6D/C3i+hxLAFNO47/y7X7LAjGSksFg5qVSv+bzfxRBSD2RtcYAn95mfq8siUty6rLoctwSOaKWPIbW17H6WERLcaA4NcN9SvBq6qlIrbTDGDpMc2OGdeU0UN7GDIY1TCPNTNt6fodnF4fP5aDhaZjGgDqiG8KeRJSB8VjQVdq4l0+/MSvtQe5OYAcYT2/MRM+0sPeICopHcoMFlTzmpjieAT6Qwm3YFjZ+9cgl4ZXu/Vm1p1CLQ9VzoFm2R0xgFpK2DvVpSeqUTOEnvxIPJlxfgkeIqbIkPpUADEUVc04o32nQxo8IlVJzAiRwqqSqhgm9DvMDbpY/EDcxr7Ee7pATdFEDuprLqSyy6RV14ws4/pyeaEP05V69rXdW0FyDF99Dup5amfDQ4WbmXMjwGns65CPh0sXd7ul1bU0KVilrC/Zr+mNKYvQGUVNmZ1a3iagM7INAkLj2BYWF1nEG6nTOERnNTHwnUPy/55jbZOSZ7yYZvH8gXQ776mAQuSjkMK30W9+02TxvRoU9L/u+QwF4ytVr+O0V8IMNi021cZvVft5APGMsNvBETrFNo0TSK1aXLOQLcLuNUvaddhkpHpPI98tmRuFBfry569PFLTpadESWFZAwoLEJurQ1Zf4//RkKogTtk="
  skip_cleanup: true
  on:
    branch: master
    tags: true
